-- AlterEnum: dedicated audit actions for streaming export evidence
ALTER TYPE "AuditAction" ADD VALUE 'EXPORT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPORT_RERUN';
ALTER TYPE "AuditAction" ADD VALUE 'EXPORT_TEMPLATE_SAVED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPORT_TEMPLATE_RUN';
ALTER TYPE "AuditAction" ADD VALUE 'EXPORT_DOWNLOAD_STARTED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPORT_DOWNLOAD_COMPLETED';
ALTER TYPE "AuditAction" ADD VALUE 'EXPORT_DOWNLOAD_FAILED';
